/**
 * Generated from contracts.yaml by scripts/gen_contracts.py.
 *
 * Do NOT edit this file. Edit contracts.yaml and run `just contracts`.
 */

/**
 * The revisions of one contract an artifact implements.
 *
 * Two peers are compatible when their ranges overlap; they then
 * operate at the lower of the two `speaks`.
 */
export interface ContractRange {
  readonly speaks: number;
  readonly accepts: number;
}

export const CONTRACTS = {
  // The wire protocol between switch-core's agent bridge and an agent runtime: the event stream, its frame shapes, the resume cursor, and the tool-call channel.
  'agent-protocol': {
    'switch-core': { speaks: 1, accepts: 1 },
    'agent-runtime': { speaks: 1, accepts: 1 },
  },
  // The HTTP API switch-core serves to first-party UI clients. Excludes the authentication surface, which is deliberately frozen and unversioned so that a client can always authenticate far enough to be told what is wrong.
  'gateway-api': {
    'switch-core': { speaks: 1, accepts: 1 },
    switchdash: { speaks: 1, accepts: 1 },
  },
  // The interface of the published standalone compose artifact — its service names, profiles, and environment variables — which switchdash's local-server mode drives.
  'stack-compose': {
    switchdash: { speaks: 1, accepts: 1 },
    compose: { speaks: 1, accepts: 1 },
  },
  // How switchdash controls a deployed sidecar on a remote host: the ready file it reads, and the control channel it opens.
  'sidecar-control': {
    switchdash: { speaks: 1, accepts: 1 },
    sidecar: { speaks: 1, accepts: 1 },
  },
  // The database schema switch-core expects. Internal to switch-core — this contract is never disclosed in an externally facing response.
  'db-schema': {
    'switch-core': { speaks: 1, accepts: 1 },
  },
} as const satisfies Record<string, Record<string, ContractRange>>;

export type ContractName = keyof typeof CONTRACTS;

/**
 * Return an artifact's declared range for a contract.
 *
 * Throws for a pair the registry does not know. An unregistered pair
 * is a bug in the caller, never a reason to assume a default — a wrong
 * default reads as compatible.
 */
export function contractRange(contract: string, artifact: string): ContractRange {
  const registry = CONTRACTS as Record<string, Record<string, ContractRange>>;
  const declared = registry[contract]?.[artifact];
  if (declared === undefined) {
    throw new Error(
      `contracts.yaml declares no range for artifact '${artifact}' in contract '${contract}'`
    );
  }
  return declared;
}
