"""add_user_auth_and_agent_owner

Revision ID: 0b93105ee525
Revises: 303c0729705c
Create Date: 2026-05-15 16:03:53.731634

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b93105ee525"
down_revision: str | None = "303c0729705c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("owner_id", sa.Text(), nullable=True))
    op.create_foreign_key(
        "fk_agents_owner_id_users", "agents", "users", ["owner_id"], ["id"]
    )
    op.add_column("users", sa.Column("password_hash", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    op.drop_constraint("fk_agents_owner_id_users", "agents", type_="foreignkey")
    op.drop_column("agents", "owner_id")
    # ### end Alembic commands ###
