"""add orchestrated to rooms

Revision ID: 303c0729705c
Revises: dad29005a7f7
Create Date: 2026-05-13 16:44:34.530210

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "303c0729705c"
down_revision: str | None = "dad29005a7f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("orchestrated", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "orchestrated")
    # ### end Alembic commands ###
