"""task protocol and agent type

Revision ID: 93bb75c91fa4
Revises: 2fdce59aecd2
Create Date: 2026-05-20 15:56:19.948223

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "93bb75c91fa4"
down_revision: str | None = "2fdce59aecd2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column(
            "agent_type", sa.Text(), nullable=False, server_default="session_polling"
        ),
    )
    op.execute("ALTER TABLE agents ALTER COLUMN agent_type DROP DEFAULT")
    op.alter_column(
        "agents",
        "integration_profile",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("agents", "api_key_id", existing_type=sa.TEXT(), nullable=False)
    op.add_column(
        "room_agents",
        sa.Column("last_connected_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "server_connectors",
        "connection_config",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.add_column(
        "tasks",
        sa.Column(
            "updates",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column("tasks", sa.Column("outcome", sa.Text(), nullable=True))
    op.add_column(
        "tasks", sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "tasks", sa.Column("finalised_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("tasks", "summary", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("tasks", "result")
    op.drop_column("tasks", "updated_at")
    op.drop_column("tasks", "error")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "tasks",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column("tasks", "summary", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("tasks", "finalised_at")
    op.drop_column("tasks", "accepted_at")
    op.drop_column("tasks", "outcome")
    op.drop_column("tasks", "updates")
    op.alter_column(
        "server_connectors",
        "connection_config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_column("room_agents", "last_connected_at")
    op.alter_column("agents", "api_key_id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "agents",
        "integration_profile",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_column("agents", "agent_type")
    # ### end Alembic commands ###
