#!/usr/bin/env python3
"""Generate the per-language contract-registry modules from contracts.yaml.

`contracts.yaml` is the only authored copy of which contract revisions each
Switch artifact speaks and accepts. Artifacts are written in different
languages and ship independently, so each needs the registry compiled in —
a running artifact cannot ask a file on someone else's disk what it speaks.

Rather than maintain one copy per language by hand, they are generated. The
alternative is already in the tree and already broken: COMPATIBLE_SWITCH_VERSION
is hand-copied into app-identity.canary.ts, held in step by a comment reading
"keep in sync" and nothing else.

Usage:
    python scripts/gen_contracts.py            # write the generated modules
    python scripts/gen_contracts.py --check    # fail if any is stale or edited

`--check` regenerates in memory and compares, so it catches both failure modes:
editing contracts.yaml without regenerating, and hand-editing a generated file.
It needs no formatter or toolchain, so CI can run it anywhere.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "contracts.yaml"

BANNER_LINES = [
    "Generated from contracts.yaml by scripts/gen_contracts.py.",
    "",
    "Do NOT edit this file. Edit contracts.yaml and run `just contracts`.",
]


@dataclass(frozen=True)
class Target:
    path: Path
    render: Any


@dataclass(frozen=True)
class Contract:
    name: str
    description: str
    artifacts: dict[str, tuple[int, int]]


def load_contracts() -> list[Contract]:
    """Parse and validate contracts.yaml.

    Validation is strict: a malformed registry is a build-time error, never a
    default. Every downstream compatibility answer rests on these numbers.
    """
    raw = yaml.safe_load(SOURCE.read_text())
    if not isinstance(raw, dict) or "contracts" not in raw:
        raise ValueError(f"{SOURCE} must have a top-level 'contracts' mapping")

    contracts: list[Contract] = []
    for name, body in raw["contracts"].items():
        if not isinstance(body, dict):
            raise ValueError(f"contract {name!r}: expected a mapping")
        description = body.get("description")
        if not description:
            raise ValueError(f"contract {name!r}: a description is required")
        artifacts_raw = body.get("artifacts")
        if not artifacts_raw:
            raise ValueError(f"contract {name!r}: at least one artifact is required")

        artifacts: dict[str, tuple[int, int]] = {}
        for artifact, decl in artifacts_raw.items():
            if not isinstance(decl, dict) or set(decl) != {"speaks", "accepts"}:
                raise ValueError(
                    f"contract {name!r}, artifact {artifact!r}: "
                    "expected exactly 'speaks' and 'accepts'"
                )
            speaks, accepts = decl["speaks"], decl["accepts"]
            for label, value in (("speaks", speaks), ("accepts", accepts)):
                if not isinstance(value, int) or isinstance(value, bool) or value < 1:
                    raise ValueError(
                        f"contract {name!r}, artifact {artifact!r}: "
                        f"{label} must be an integer >= 1, got {value!r}"
                    )
            if accepts > speaks:
                raise ValueError(
                    f"contract {name!r}, artifact {artifact!r}: "
                    f"accepts ({accepts}) is above speaks ({speaks}), "
                    "which declares an empty range"
                )
            artifacts[artifact] = (speaks, accepts)

        contracts.append(
            Contract(
                name=name,
                description=" ".join(str(description).split()),
                artifacts=artifacts,
            )
        )
    return contracts


def render_python(contracts: list[Contract]) -> str:
    lines = ['"""' + BANNER_LINES[0], ""]
    lines.extend(BANNER_LINES[2:])
    lines.append('"""')
    lines.append("")
    lines.append("from typing import Final, NamedTuple")
    lines.append("")
    lines.append("")
    lines.append("class ContractRange(NamedTuple):")
    lines.append('    """The revisions of one contract an artifact implements.')
    lines.append("")
    lines.append("    Two peers are compatible when their ranges overlap; they then")
    lines.append("    operate at the lower of the two `speaks`.")
    lines.append('    """')
    lines.append("")
    lines.append("    speaks: int")
    lines.append("    accepts: int")
    lines.append("")
    lines.append("")
    lines.append("CONTRACTS: Final[dict[str, dict[str, ContractRange]]] = {")
    for contract in contracts:
        lines.append(f"    # {contract.description}")
        lines.append(f'    "{contract.name}": {{')
        for artifact, (speaks, accepts) in contract.artifacts.items():
            lines.append(
                f'        "{artifact}": ContractRange(speaks={speaks}, accepts={accepts}),'
            )
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def contract_range(contract: str, artifact: str) -> ContractRange:")
    lines.append('    """Return an artifact\'s declared range for a contract.')
    lines.append("")
    lines.append("    Raises KeyError for a pair the registry does not know. An")
    lines.append("    unregistered pair is a bug in the caller, never a reason to")
    lines.append("    assume a default — a wrong default reads as compatible.")
    lines.append('    """')
    lines.append("    try:")
    lines.append("        return CONTRACTS[contract][artifact]")
    lines.append("    except KeyError:")
    lines.append("        raise KeyError(")
    lines.append(
        '            f"contracts.yaml declares no range for artifact {artifact!r} "'
    )
    lines.append('            f"in contract {contract!r}"')
    lines.append("        ) from None")
    lines.append("")
    return "\n".join(lines)


def ts_key(name: str) -> str:
    """Quote an object key only when it is not a bare JS identifier.

    Matches what the repo's formatter would produce, so the generated file is
    a fixed point of `oxfmt` and `--check` needs no formatter to run.
    """
    if name.isidentifier() and name.isascii():
        return name
    return f"'{name}'"


def render_typescript(contracts: list[Contract]) -> str:
    lines = ["/**"]
    for banner in BANNER_LINES:
        lines.append(f" * {banner}".rstrip())
    lines.append(" */")
    lines.append("")
    lines.append("/**")
    lines.append(" * The revisions of one contract an artifact implements.")
    lines.append(" *")
    lines.append(" * Two peers are compatible when their ranges overlap; they then")
    lines.append(" * operate at the lower of the two `speaks`.")
    lines.append(" */")
    lines.append("export interface ContractRange {")
    lines.append("  readonly speaks: number;")
    lines.append("  readonly accepts: number;")
    lines.append("}")
    lines.append("")
    lines.append("export const CONTRACTS = {")
    for contract in contracts:
        lines.append(f"  // {contract.description}")
        lines.append(f"  {ts_key(contract.name)}: {{")
        for artifact, (speaks, accepts) in contract.artifacts.items():
            lines.append(
                f"    {ts_key(artifact)}: {{ speaks: {speaks}, accepts: {accepts} }},"
            )
        lines.append("  },")
    lines.append("} as const satisfies Record<string, Record<string, ContractRange>>;")
    lines.append("")
    lines.append("export type ContractName = keyof typeof CONTRACTS;")
    lines.append("")
    lines.append("/**")
    lines.append(" * Return an artifact's declared range for a contract.")
    lines.append(" *")
    lines.append(
        " * Throws for a pair the registry does not know. An unregistered pair"
    )
    lines.append(
        " * is a bug in the caller, never a reason to assume a default — a wrong"
    )
    lines.append(" * default reads as compatible.")
    lines.append(" */")
    lines.append(
        "export function contractRange(contract: string, artifact: string): ContractRange {"
    )
    lines.append(
        "  const registry = CONTRACTS as Record<string, Record<string, ContractRange>>;"
    )
    lines.append("  const declared = registry[contract]?.[artifact];")
    lines.append("  if (declared === undefined) {")
    lines.append("    throw new Error(")
    lines.append(
        "      `contracts.yaml declares no range for artifact '${artifact}' in contract '${contract}'`"
    )
    lines.append("    );")
    lines.append("  }")
    lines.append("  return declared;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


TARGETS = [
    # switch-core: the agent bridge, the gateway API, and the schema check.
    Target(REPO_ROOT / "core" / "switch_core" / "contracts.py", render_python),
    # switchdash: the desktop app and the sidecar it bundles and deploys.
    Target(
        REPO_ROOT / "dash" / "packages" / "shared" / "src" / "contracts.ts",
        render_typescript,
    ),
    # agent-runtime: published to a registry, so it cannot depend on the
    # unpublished workspace package above and carries its own copy.
    Target(
        REPO_ROOT
        / "dash"
        / "packages"
        / "switch-agent-runtime"
        / "src"
        / "contracts.ts",
        render_typescript,
    ),
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if any generated module differs from what would be written",
    )
    args = parser.parse_args()

    contracts = load_contracts()
    stale: list[Path] = []

    for target in TARGETS:
        expected = target.render(contracts)
        relative = target.path.relative_to(REPO_ROOT)
        if args.check:
            actual = target.path.read_text() if target.path.exists() else None
            if actual != expected:
                stale.append(relative)
            continue
        target.path.parent.mkdir(parents=True, exist_ok=True)
        target.path.write_text(expected)
        print(f"wrote {relative}")

    if stale:
        print(
            "Generated contract modules are out of date:\n"
            + "\n".join(f"  {path}" for path in stale)
            + "\n\nEither contracts.yaml changed without regenerating, or a generated\n"
            "file was hand-edited. Run `just contracts` and commit the result.",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("Generated contract modules are up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
