apiVersion: v1
kind: Service
metadata:
  name: {{ include "switch.switchCoreHost" . }}
  labels:
    {{- include "switch.labels" . | nindent 4 }}
    {{- include "switch.selectorLabels" (dict "Release" .Release "component" "switch-core") | nindent 4 }}
spec:
  type: {{ .Values.switchCore.service.type }}
  ports:
    - port: {{ .Values.switchCore.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "switch.selectorLabels" (dict "Release" .Release "component" "switch-core") | nindent 4 }}
